// <auto-generated />
using System;
using ABM.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ABM.Migrations
{
    [DbContext(typeof(AppDBContext))]
    [Migration("20250407051207_AddCODOTCColumnaMeses")]
    partial class AddCODOTCColumnaMeses
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("ABM.Models.Gerencia", b =>
                {
                    b.Property<int>("ID_gerencia")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID_gerencia"), 1L, 1);

                    b.Property<string>("Nom_Gerencia")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("ID_gerencia");

                    b.ToTable("im_gerencia", (string)null);
                });

            modelBuilder.Entity("ABM.Models.Rol", b =>
                {
                    b.Property<int>("idRol")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("idRol"), 1L, 1);

                    b.Property<string>("nombre")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("idRol");

                    b.ToTable("Rol", (string)null);
                });

            modelBuilder.Entity("ABM.Models.Subgerencia", b =>
                {
                    b.Property<int>("ID_Subgerencia")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID_Subgerencia"), 1L, 1);

                    b.Property<int>("COD_Gerencia")
                        .HasColumnType("int");

                    b.Property<string>("Nom_Subgerencia")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("ID_Subgerencia");

                    b.HasIndex("COD_Gerencia");

                    b.ToTable("im_Subgerencias", (string)null);
                });

            modelBuilder.Entity("ABM.Models.Usuario", b =>
                {
                    b.Property<int>("IdUsuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdUsuario"), 1L, 1);

                    b.Property<int?>("COD_OTC")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ExpiracionToken")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaCambioPassword")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ID_Subgerencia")
                        .HasColumnType("int");

                    b.Property<int?>("ID_gerencia")
                        .HasColumnType("int");

                    b.Property<int>("MesesExpiracionClave")
                        .HasColumnType("int");

                    b.Property<bool?>("ResponsableFirma")
                        .HasColumnType("bit");

                    b.Property<string>("TokenRecuperacion")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("correo")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("estado")
                        .HasColumnType("char(1)");

                    b.Property<string>("firma")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("idRol")
                        .HasColumnType("int");

                    b.Property<string>("nombre")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("password")
                        .HasColumnType("varchar(max)");

                    b.Property<string>("password_c")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("IdUsuario");

                    b.HasIndex("ID_Subgerencia");

                    b.HasIndex("ID_gerencia");

                    b.HasIndex("idRol");

                    b.ToTable("Usuario", (string)null);
                });

            modelBuilder.Entity("ABM.Models.Subgerencia", b =>
                {
                    b.HasOne("ABM.Models.Gerencia", "Gerencia")
                        .WithMany()
                        .HasForeignKey("COD_Gerencia")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Gerencia");
                });

            modelBuilder.Entity("ABM.Models.Usuario", b =>
                {
                    b.HasOne("ABM.Models.Subgerencia", "Subgerencia")
                        .WithMany()
                        .HasForeignKey("ID_Subgerencia");

                    b.HasOne("ABM.Models.Gerencia", "Gerencia")
                        .WithMany()
                        .HasForeignKey("ID_gerencia");

                    b.HasOne("ABM.Models.Rol", "Rol")
                        .WithMany()
                        .HasForeignKey("idRol");

                    b.Navigation("Gerencia");

                    b.Navigation("Rol");

                    b.Navigation("Subgerencia");
                });
#pragma warning restore 612, 618
        }
    }
}
